fix: Handle ESM Tailwindconfigs (fix #667)
histoire-dev/histoire pull request #723
Opened 2024-05-26 15:17 UTC by schwarmco

### Description

Fixes #667

When using ESMs `export default` instead of `module.exports` in `tailwind.config.{js,ts}` the tailwindConfig is nested in a `default` key which then incorrectly merges with tailwinds default config like this:

<img width="272" alt="image" src="https://github.com/histoire-dev/histoire/assets/18698995/e07e099e-0f55-4a5a-8ac1-b64328ad96a6">

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [ ] If it's a new feature, provide a convincing reason to add it. *Ideally, you should open a suggestion issue first and have it approved before working on it.*
- [x] Read the [Contributing Guidelines](https://github.com/Akryum/histoire/blob/main/CONTRIBUTING.md).
- [x] Read the [Pull Request Guidelines](https://github.com/Akryum/histoire/blob/main/CONTRIBUTING.md#pull-request-guidelines) and follow the [Commit Convention](https://github.com/Akryum/histoire/blob/main/.github/commit-convention.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2024-06-08 13:10 UTC, bahulneel requested changes
The patch didn't work for me as the tailwind plugins (i.e. backgroundColours, etc.) that the tailwind storyTemplate expects were not being generated. After reading the documentation, I noticed that resolveConfig needed to run on with the tailwind config at the base of the imported object, not just the storyTemplate function.

2024-06-08 13:10 UTC, bahulneel commented on packages/histoire/src/node/builtin-plugins/tailwind-tokens.ts
>        const resolvedTailwindConfig = resolveConfig(tailwindConfig)
```suggestion
      const resolvedTailwindConfig = resolveConfig(tailwindConfig.default ?? tailwindConfig)
```

2024-06-08 13:10 UTC, bahulneel commented on packages/histoire/src/node/builtin-plugins/tailwind-tokens.ts
> +      await api.fs.writeFile(storyFile, storyTemplate(resolvedTailwindConfig.default ?? resolvedTailwindConfig))
```suggestion
      await api.fs.writeFile(storyFile, storyTemplate(resolvedTailwindConfig))
```

2024-06-14 06:50 UTC, schwarmco commented
Thank you for the feedback @bahulneel - i didn't run into that problem but i guess it depends on the ts environment you're in. As your suggestions were optional chained i've pulled them in the PR.

2024-07-15 15:21 UTC, waldemarennsaed reviewed
IMO that looks correct ... well done.

2024-07-15 15:23 UTC, waldemarennsaed commented
Anything blocking from merging this?

2024-07-17 07:23 UTC, waldemarennsaed commented
This would be nice to be merged. I have the current issue of:
- keeping a default tailwind config that overwrites tailwind colors and other theme-related stuff
- only working if exporting tailwind as `module.exports`

Then, I need to import my tailwind theme object in JavaScript, e.g. in one of my stories like that:

```vue
<script setup lang="ts">
import resolveConfig from 'tailwindcss/resolveConfig'
import tailwindConfig from '../../../../tailwind.config.js'

const fullConfig = resolveConfig(tailwindConfig)
</script>
```

Resulting in the following error:
![Bildschirmfoto 2024-07-17 um 09 20 10](https://github.com/user-attachments/assets/c9cb9093-fd2b-4ea0-8661-765acff9572f)
![Bildschirmfoto 2024-07-17 um 09 22 49](https://github.com/user-attachments/assets/4c54ec9b-6e27-4b3e-9137-b6e10ed9f305)

I am pretty sure that this MR will fix this issue for me, since I will be able to keep a correct Tailwind Story and will be able to export my tailwind config as ESM.

2024-08-01 07:52 UTC, waldemarennsaed commented
@schwarmco not intending to annoy anyone but ... any blockers on this? Or this be merged?

2024-08-01 07:56 UTC, schwarmco commented
not annoying at all @waldemarennsaed - i'd love to get this merged too but i'm not a maintainer of histoire. i am actively using that patch on my projects

2024-08-01 07:58 UTC, waldemarennsaed commented
@Akryum I don't know who else I could mention here - can you maybe bring some life to this MR? 🤓

2024-08-22 13:29 UTC, merged